version: "3"
services:
    aws-cdk-py:
        command: /bin/bash
        build: .
        volumes:
            - ./app:/root/app
        environment: 
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        tty: true